# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='注册邮箱')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='昵称')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('coin', models.IntegerField(default=0, verbose_name='硬币')),
                ('avatar', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('verify_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='验证码')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='验证码失效时间')),
                ('role', models.IntegerField(choices=[(0, '管理员'), (1, '普通用户'), (2, '访客')], verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, verbose_name='名称')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('avatar_url', models.URLField(blank=True, max_length=255, verbose_name='头像url')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='token失效时间')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='access_token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh_token')),
                ('provider', models.IntegerField(choices=[(0, 'Github'), (1, 'QQ'), (2, 'Coding'), (3, '新浪微博')], verbose_name='类别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
