# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160530_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_code',
        ),
        migrations.AddField(
            model_name='user',
            name='alink_verify_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='激活链接验证码'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_alink_verify_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上一次激活链接发送请求验证码请求时间'),
        ),
    ]
