# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160531_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
    ]
