# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160603_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(default='https://dn-joway.qbox.me/1465087838481_user_116px_1196112_easyicon.net.png', max_length=255, verbose_name='头像'),
        ),
    ]
