web:  
  restart: always 
  build: ./
  expose:
    - "80"
  links: 
    - redis:redis
  volumes: 
    - /var/log
#  command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

mysql:
  restart: always
  image: mysql:latest
  volumes_from:
    - data
  ports:
    - "3306"

redis:  
  restart: always
  image: redis:latest 
  ports: 
    - "6379"

elastic:
  restart: always
  build: ./.deploy/elastic/
  expose:
    - "9200"
    - "9300"
  volumes:
    - /logs
    - /data


data:
  restart: always 
  image: mysql:latest
  volumes: 
    - /var/lib/mysql
  command: true